apiVersion: apps/v1
kind: Deployment
metadata:
  name: holamundo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holamundo
  template:
    metadata:
      labels:
        app: holamundo
    spec:
      containers:
      - name: holamundo-container
        image: tu_usuario_docker/holamundo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: holamundo-service
spec:
  type: LoadBalancer
  selector:
    app: holamundo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

