apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: minodo-rxv6o/myapp-image:latest # Reemplaza esto con la imagen de tu aplicación en Docker Hub
        ports:
        - containerPort: 80
